### ISSUE TITLE
GraalVM example?

### ISSUE THREAD

**Issue by jmfayard** [jamesward/hello-micronaut#2]
Hello James

It was nice to see you in Copenhagen

I was wondering if running Micronaut on Google Cloud Run + GraalVM was possible

**Comment by jamesward** [comment]
Hey there!  I'm actually working on getting this sample GraalVM + Cloud Shell ified.  :)  Will let you know when I have it working.

**Comment by jamesward** [comment]
It works! https://github.com/jamesward/hello-micronaut/tree/graalvm

Verifying on Cloud Run now.

**Comment by jamesward** [comment]
I'm having problems getting Cloud Shell to build the native image.  But you should be fine building locally or on Cloud Build, then deploying on Cloud Run.
